# Generated by Django 5.1.1 on 2025-03-24 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="date",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Collection Date"
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
