# Generated by Django 5.1.1 on 2025-03-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_collection_date_alter_purchase_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="outstanding",
            options={"ordering": ["bill_no"], "verbose_name_plural": "Outstanding"},
        ),
        migrations.RemoveField(
            model_name="product",
            name="pur_price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="sale_price",
        ),
        migrations.AddField(
            model_name="product",
            name="dpl",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="collection",
            name="amt",
            field=models.FloatField(verbose_name="Total Collection"),
        ),
    ]
