# Generated by Django 5.1.1 on 2025-03-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_outstanding_options_remove_product_pur_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseproduct",
            name="qty",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="saleproduct",
            name="price",
            field=models.FloatField(verbose_name="Sale Price / Unit"),
        ),
        migrations.AlterField(
            model_name="saleproduct",
            name="qty",
            field=models.IntegerField(),
        ),
    ]
