# Generated by Django 5.1.1 on 2025-03-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_purchaseproduct_qty_alter_saleproduct_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseproduct",
            name="base_rate",
            field=models.FloatField(default=None, verbose_name="Base Rate / Unit"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="purchaseproduct",
            name="discount",
            field=models.FloatField(default=None, verbose_name="Total Discount"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="purchaseproduct",
            name="price",
            field=models.FloatField(verbose_name="Purchase Price / Unit"),
        ),
    ]
