# Generated by Django 5.1.1 on 2025-03-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_outstanding_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outstanding",
            name="customer",
            field=models.CharField(max_length=100),
        ),
    ]
