# Generated by Django 5.1.1 on 2025-03-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_outstanding_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="mrp",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="base",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="dpl",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="opening_stock",
            field=models.IntegerField(default=0),
        ),
    ]
