# Generated by Django 5.1.7 on 2025-03-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_product_dpl"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="city",
            field=models.CharField(default="Trichy", max_length=100),
        ),
        migrations.AddField(
            model_name="customer",
            name="pincode",
            field=models.CharField(default="620001", max_length=100),
        ),
    ]
