# Generated by Django 5.1.7 on 2025-03-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_saleproduct_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="city",
            field=models.CharField(
                db_default="Trichy", default="Trichy", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="pincode",
            field=models.CharField(
                db_default="620001", default="620001", max_length=100
            ),
        ),
    ]
