# Generated by Django 5.1.7 on 2025-03-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_alter_customer_opening_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saleproduct",
            name="color",
            field=models.IntegerField(blank=True, null=True, verbose_name="Color"),
        ),
    ]
