# Generated by Django 5.1.1 on 2025-03-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_alter_saleproduct_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseproduct",
            name="price",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Purchase Price / Unit"
            ),
        ),
    ]
