# Generated by Django 5.1.1 on 2025-03-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_alter_purchaseproduct_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="phone",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
