# Generated by Django 5.1.1 on 2025-03-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_alter_supplier_address_alter_supplier_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="discount",
            field=models.IntegerField(db_default=0, default=0, verbose_name="Discount"),
        ),
    ]
