# Generated by Django 5.1.1 on 2025-03-31 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_sale_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionbillentry",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bills",
                to="app.collection",
            ),
        ),
    ]
