# Generated by Django 5.1.1 on 2025-04-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_alter_collectionbillentry_collection"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="discount",
            field=models.FloatField(db_default=0, default=0, verbose_name="Discount"),
        ),
    ]
