# Generated by Django 5.1.1 on 2025-04-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_collection_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="referral",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
