# Generated by Django 5.1.1 on 2025-04-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_customer_referral"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saleproduct",
            name="color",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Color"
            ),
        ),
    ]
